env:
  CIRRUS_CLONE_DEPTH: 1
  CAIDE_USE_SYSTEM_CLANG: 'ON'
  CAIDE_CLANG_VERSION: ''

ubuntu_task:
  name: Ubuntu Xenial CAIDE_CLANG_VERSION=$CAIDE_CLANG_VERSION CAIDE_USE_SYSTEM_CLANG=$CAIDE_USE_SYSTEM_CLANG
  container:
    image: ubuntu:xenial
  timeout_in: 2h

  env:
    matrix:
      # - CAIDE_USE_SYSTEM_CLANG: 'OFF'
      - CAIDE_CLANG_VERSION: '3.8'
      - CAIDE_CLANG_VERSION: '3.9'
      - CAIDE_CLANG_VERSION: '4.0'
      - CAIDE_CLANG_VERSION: '5.0'
      - CAIDE_CLANG_VERSION: '6.0'
      - CAIDE_CLANG_VERSION: 7
      - CAIDE_CLANG_VERSION: 8
      - CAIDE_CLANG_VERSION: 9
      - CAIDE_CLANG_VERSION: 10
      - CAIDE_CLANG_VERSION: 11

  apt1_cache:
    folder: /var/cache/apt
    fingerprint_script: echo apt1 $CIRRUS_OS
    reupload_on_changes: true

  apt2_cache:
    folder: /var/lib/apt/lists
    fingerprint_script: echo apt2 $CIRRUS_OS
    reupload_on_changes: true

  ccache_cache:
    folder: ccache-cache
    fingerprint_script: echo ccache $CIRRUS_OS $CAIDE_USE_SYSTEM_CLANG $CAIDE_CLANG_VERSION
    reupload_on_changes: true

  script: ci/cirrus-script.sh

freebsd_task:
  name: FreeBSD
  freebsd_instance:
    image_family: freebsd-12-1
  timeout_in: 2h

  env:
    CAIDE_USE_SYSTEM_CLANG: 'OFF'

  ccache_cache:
    folder: ccache-cache
    fingerprint_script: echo ccache $CIRRUS_OS $CAIDE_USE_SYSTEM_CLANG $CAIDE_CLANG_VERSION
    reupload_on_changes: true

  script:
    - pkg update -f
    - pkg install -y bash
    - bash ci/cirrus-script.sh

