env:
  CIRRUS_CLONE_DEPTH: 1
  CAIDE_USE_SYSTEM_CLANG: 'ON'
  CAIDE_CLANG_VERSION: ''

freebsd_task:
  name: FreeBSD
  freebsd_instance:
    image_family: freebsd-12-2
  timeout_in: 2h

  env:
    CAIDE_USE_SYSTEM_CLANG: 'OFF'

  # pkg_cache:
  #   folder: /var/cache/pkg
  #   fingerprint_script: echo pkg $CIRRUS_OS
  #   reupload_on_changes: true

  # pkgdb_cache:
  #   folder: /var/db/pkg
  #   fingerprint_script: echo pkgdb $CIRRUS_OS
  #   reupload_on_changes: true

  ccache_cache:
    folder: ccache-cache
    fingerprint_script: echo ccache $CIRRUS_OS $CAIDE_USE_SYSTEM_CLANG $CAIDE_CLANG_VERSION ver1
    reupload_on_changes: true

  install_script:
    - pkg update -f
    - pkg install -y bash

  script: bash ci/cirrus-script.sh

# ubuntu_task:
#   name: Ubuntu Xenial clang $CAIDE_CLANG_VERSION system_clang=$CAIDE_USE_SYSTEM_CLANG
#   container:
#     image: ubuntu:xenial
#     cpu: 1
#     memory: 1G

#   matrix:
#     - env: {CAIDE_USE_SYSTEM_CLANG: 'OFF'}
#       timeout_in: 2h
#       container:
#         cpu: 2
#         memory: 3G
#     - env: {CAIDE_CLANG_VERSION: '3.8'}
#     - env: {CAIDE_CLANG_VERSION: '3.9'}
#     - env: {CAIDE_CLANG_VERSION: '4.0'}
#     - env: {CAIDE_CLANG_VERSION: '5.0'}
#     - env: {CAIDE_CLANG_VERSION: '6.0'}
#     - env: {CAIDE_CLANG_VERSION: 7}
#     - env: {CAIDE_CLANG_VERSION: 8}
#     - env: {CAIDE_CLANG_VERSION: 9}
#     - env: {CAIDE_CLANG_VERSION: 10}
#     - env: {CAIDE_CLANG_VERSION: 11}

#   # apt1_cache:
#   #   folder: /var/cache/apt
#   #   fingerprint_script: echo apt1 $CIRRUS_OS ver1
#   #   reupload_on_changes: true

#   apt2_cache:
#     folder: /var/lib/apt/lists
#     fingerprint_script: echo apt2 $CIRRUS_OS ver1
#     reupload_on_changes: true

#   ccache_cache:
#     folder: ccache-cache
#     fingerprint_script: echo ccache $CIRRUS_OS $CAIDE_USE_SYSTEM_CLANG $CAIDE_CLANG_VERSION
#     reupload_on_changes: true

#   script: ci/cirrus-script.sh

