Build and test:
  image: 'ubuntu:xenial'
  script: ci/gitlab-script.sh
  timeout: 1 hour
  cache:
    key: "$CAIDE_USE_SYSTEM_CLANG $CAIDE_CLANG_VERSION"
    paths:
      - ~/.ccache/
  parallel:
    matrix:
      - CAIDE_USE_SYSTEM_CLANG: 'OFF'
      - CAIDE_USE_SYSTEM_CLANG: 'ON'
        CAIDE_CLANG_VERSION: ['3.8', '3.9', '4.0', '5.0', '6.0', 7, 8, 9, 10, 11]

