Build and test:
  image: 'debian:bullseye'
  script: ci/gitlab-script.sh
  timeout: 3 hours

  cache:
    key: "ccache:os=debian-bullseye:systemclang=$CAIDE_USE_SYSTEM_CLANG:clang=$CAIDE_CLANG_VERSION"
    paths: [ 'ccache-cache' ]

  artifacts:
    paths:
      - cmd

  parallel:
    matrix:
      - CAIDE_USE_SYSTEM_CLANG: 'OFF'
      - CAIDE_USE_SYSTEM_CLANG: 'ON'
        # https://apt.llvm.org/llvm.sh installation script only supports versions starting at 9
        CAIDE_CLANG_VERSION: [9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
