Build and test:
  image: 'ubuntu:xenial'
  script: ci/gitlab-script.sh
  timeout: 2 hours

  cache:
    key: "ccache-systemclang=$CAIDE_USE_SYSTEM_CLANG-clang=$CAIDE_CLANG_VERSION"
    paths: [ 'ccache-cache' ]

  artifacts:
    paths:
      - cmd

  parallel:
    matrix:
      - CAIDE_USE_SYSTEM_CLANG: 'OFF'
      - CAIDE_USE_SYSTEM_CLANG: 'ON'
        CAIDE_CLANG_VERSION: ['3.8', '3.9', '4.0', '5.0', '6.0', 7, 8, 9, 10, 11]

